steps:
- name: node:10.15.1
  entrypoint: npm
  args:
  - 'install'
  dir: 'blenz.dev'

- name: node:10.15.1
  entrypoint: npm
  args:
  - 'run'
  - 'build'
  dir: 'blenz.dev'

- name: 'gcr.io/green-tract-254701/firebase'
  args:
  - 'deploy'
