steps:
- name: node:10.15.1
  entrypoint: npm
  args:
  - 'install'
  dir: 'blenz.dev'

- name: node:10.15.1
  entrypoint: npm
  args:
  - 'run'
  - 'build'
  dir: 'blenz.dev'

- name: 'gcr.io/green-tract-254701/firebase'
  entrypoint: 'bash'
  args:
  - 'deploy'
  - '--token'
  - '$$FIREBASE_TOKEN'
  secretEnv:
  - 'FIREBASE_TOKEN'

secrets:
- kmsKeyName: projects/green-tract-254701/locations/global/keyRings/blenz-dev/cryptoKeys/firebase-access-token
  secretEnv:
    FIREBASE_TOKEN: CiQAbFIF3zxqImdRcMgdCgKAht9brMDcp/oFSZyGpGEdYuddScQSVgCwmm6w42bANwRnBxEF0BhCo+WqVI4tIzA9CztuQpsoMsKz74NhhiSuOeKacieulzTllQDJO34cAwB96XvAekSYqOQ8Qcuo/7S0lrA4ZF+lfOhkJ7z+
