steps:
- name: node:10.15.1
  entrypoint: npm
  args:
  - 'install'
  dir: 'blenz.dev'

- name: node:10.15.1
  entrypoint: npm
  args:
  - 'run'
  - 'build'
  dir: 'blenz.dev'

- name: 'gcr.io/green-tract-254701/firebase'
  args:
  - 'deploy'
  secretEnv:
  - 'FIREBASE_TOKEN'

secrets:
- kmsKeyName: projects/green-tract-254701/locations/global/keyRings/blenz-dev/cryptoKeys/firebase-access-token
  secretEnv:
    FIREBASE_TOKEN: CiQAbFIF30hHMDOGoKX41EJET+KgyT+ONI2qEgaBNL/rAaBKbiISkAEAsJpusLIrAh3p1b6flXJLSXJBpQiQC5jD3Tq/nw16MgmL3w8JkjLpOnuOunC3iqJfWjp1Q8vl3xWbyOBF/e9l+USFciO0LUapQjlFrECDOO468wPyp1yfjHDsIMewKolmIx/WLjTlIwSEc8S9vKy4t87vNgXfADnh2TGJStdRFwcBc4KhxfKbXShcG348hrA=
