steps:
- name: gcr.io/cloud-builders/gcloud
  args:
  - 'kms',
  - 'decrypt',
  - '--ciphertext-file=secrets.json.enc',
  - '--plaintext-file=secrets.json',
  - '--location=global',
  - '--keyring=blenz-dev',
  - '--key=firebase-access-token'

- name: node:10.15.1
  entrypoint: npm
  args:
  - 'install'
  dir: 'blenz.dev'

- name: node:10.15.1
  entrypoint: npm
  args:
  - 'run'
  - 'build'
  dir: 'blenz.dev'

- name: 'gcr.io/green-tract-254701/firebase'
  args:
  - 'deploy'
  - '--token'
  - '$$FIREBASE_ACCESS_TOKEN'
  secretEnv:
  - 'FIREBASE_ACCESS_TOKEN'

secrets:
- kmsKeyName: projects/green-tract-254701/locations/global/keyRings/blenz-dev/cryptoKeys/firebase-access-token
  secretEnv:
      FIREBASE_ACCESS_TOKEN: CiQAbFIF3/O01QpiMHvYJB6iMHP+jKkn2LnjWSKePXBolEExHU0SawCwmm6w3cokE9grusfgRlZe5BSDK+6fNqC4/QMCzFehJYP9IE1P2TVtgzcWpj1YN0qiw49CYJisBbzqI3jR/Jl+h1eO/DNXCqWeAHG1SzKHSiy7NXruvdSo2Dz+Szvk0rxLKnntpjW0dv9r
